### PR TITLE
Modify references to images in the readme and report

### PR DESCRIPTION
**Pull request by ChadNeald**

### CODE REVIEW

**Review by rtaph — CHANGES_REQUESTED** [review]
Great work! ::clap:: A few minor thoughts for this PR:

- I propose we remove the `README.html` and `doc/bc_election_turnout_report.tex` files from the PR.
- I am not sure why `rmarkdown::render()` is keeping this `.tex` intermediate file. I would have thought that it would have deleted it since the default is `clean = TRUE`. Maybe it's from a previous run that terminated early (errored)? Can we try deleting it and see if it pops back if we run the shell script? If it does, maybe we can add a tex pattern to our gitignore (along with README.html).

**Review by kmoravej — APPROVED** [review]

**Comment by ChadNeald** [comment]
> Great work! :👏: A few minor thoughts for this PR:
> 
> * I propose we remove the `README.html` and `doc/bc_election_turnout_report.tex` files from the PR.
> * I am not sure why `rmarkdown::render()` is keeping this `.tex` intermediate file. I would have thought that it would have deleted it since the default is `clean = TRUE`. Maybe it's from a previous run that terminated early (errored)? Can we try deleting it and see if it pops back if we run the shell script? If it does, maybe we can add a tex pattern to our gitignore (along with README.html).

I may be confused here but when we run the shell script it will generate an html file because the output is set to github_document. So if we don't want the html I could just remove the readme part from the shell script.

Also regarding the .tex file I'm just going to add a line in the bash script to delete it at the end since it keeps popping up even after rerunning.

**Comment by rtaph** [comment]
Sounds good to me! I thought maybe the html was only generated in interactive mode in Rstudio, but checking it now I think it generates it at the command line as well. I don't have a strong opinion about whether to commit the html report or not. I would say, let's go with whatever we have now.

Thanks, Chad!

> I may be confused here but when we run the shell script it will generate an html file because the output is set to github_document. So if we don't want the html I could just remove the readme part from the shell script.
> 
> Also regarding the .tex file I'm just going to add a line in the bash script to delete it at the end since it keeps popping up even after rerunning.

**Review by rtaph — APPROVED** [review]

**Comment by ChadNeald** [comment]
Something I just noticed is that the report md file isn't rendering the images now. Anyone know why this might be? Other than that I'm pretty happy with it all. The shell script has also been edited to include the new script names.

**Comment by rtaph** [comment]
Darn! You're right. Shall we try to remove `here::here()`? I think it's resolving to full local plath, which is not what we want for `.md`.

**Comment by ChadNeald** [comment]
Good call on removing here that seems to have fixed it. Ok I think this is ready to merge in finally. After this I think it's just merging in everyone's new script with the correct name and usage.

**Pull request merged**
