### PR TITLE
Add a code of conduct

### LINKED ISSUE #2: Add a Code of Conduct File

### PR DESCRIPTION
**Pull request by rtaph**
This PR introduces a `CONTRIBUTING.md` guidance document, along with a code of conduct.

### CODE REVIEW

**Comment by rtaph** [comment]
Oops! I realized I did too much and that the @Kamal12073 will be working on the contributing file via #3. I can remove that bit from the PR.

**Comment by rtaph** [comment]
Okay, CONTRIBUTING file removed from this PR. If we're happy with it, I would recommend a squash-merge into main.

**Comment by ChadNeald** [comment]
@rtaph everything looks good only thing I was wondering about is if we should put something here "[INSERT CONTACT METHOD]" under the Enforcement section. Just looks a little strange but I guess we also don't have a project email or anything. We could maybe just cut the sentence off at "Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement."

**Comment by rtaph** [comment]
Good catch! Yeah, I think it's probably easiest to cut that out, since it should not be hard to identify the administrators on the repo anyhow. I'll send an update to the PR in a few minutes.

**Review by ChadNeald — APPROVED** [review]

**Pull request merged**
